fps : 30
length: 24
video_path: "$HOME/projects/spatial-model/video1.mp4"
input_shape: [320,40,3]
noise: 0.05
final_degree: 2
layerconfig:
  - [10,10,5,5,441,2]
  - [7,3,4,4,30,2]
  - [15,2,1,1,1,2]
components: 32
batch_size: 32